<a href="https://colab.research.google.com/github/pradeekamanickam/datascience/blob/main/DS04(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#create 1d arr
X= np.array([1,2,3,4,5])
#create 2d arr
Y= np.array([[1,2,3],[4,5,6],[7,8,9]])
#create 3d arr
Z= np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(X)
print(Y)
print(Z)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
